'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';

interface SavedNote {
  id: string;
  title: string;
  channelTitle: string;
  duration: string;
  keyInsight: string;
  youtubeUrl: string;
  createdAt: string;
  sections?: any[];
}

export default function MyNotesPage() {
  const [savedNotes, setSavedNotes] = useState<SavedNote[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [filteredNotes, setFilteredNotes] = useState<SavedNote[]>([]);

  useEffect(() => {
    // 저장된 노트 불러오기
    const notes = JSON.parse(localStorage.getItem('saved_notes') || '[]');
    setSavedNotes(notes);
    setFilteredNotes(notes);
  }, []);

  useEffect(() => {
    // 검색 필터링
    if (searchTerm) {
      const filtered = savedNotes.filter(note => 
        note.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
        note.channelTitle.toLowerCase().includes(searchTerm.toLowerCase()) ||
        note.keyInsight.toLowerCase().includes(searchTerm.toLowerCase())
      );
      setFilteredNotes(filtered);
    } else {
      setFilteredNotes(savedNotes);
    }
  }, [searchTerm, savedNotes]);

  const deleteNote = (id: string) => {
    if (confirm('이 노트를 삭제하시겠습니까?')) {
      const updatedNotes = savedNotes.filter(note => note.id !== id);
      setSavedNotes(updatedNotes);
      localStorage.setItem('saved_notes', JSON.stringify(updatedNotes));
    }
  };

  const clearAllNotes = () => {
    if (confirm('모든 노트를 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.')) {
      setSavedNotes([]);
      localStorage.removeItem('saved_notes');
    }
  };

  const downloadNote = (note: SavedNote) => {
    const markdownContent = `# ${note.title}

**채널:** ${note.channelTitle}
**영상 길이:** ${note.duration}
**YouTube:** ${note.youtubeUrl}
**생성일:** ${new Date(note.createdAt).toLocaleDateString('ko-KR')}

## 🎯 핵심 인사이트
${note.keyInsight}

## 📝 타임스탬프별 정리

${note.sections?.map((section: any) => `
### 📍 [${section.timeRange}] ${section.title}

**핵심 내용:**
${section.content}

**💡 핵심 개념:** ${section.keyConcepts?.join(', ') || ''}
**⚡ 액션 포인트:** ${section.actionPoints?.join(', ') || ''}

---
`).join('') || ''}

## ✅ 학습 체크리스트

- [ ] 영상 시청 완료
- [ ] 핵심 개념 이해
- [ ] 액션 포인트 실행
- [ ] 복습 완료

---
*Generated by YouTube Learning Note Generator*
`;

    const blob = new Blob([markdownContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${note.title.replace(/[^a-zA-Z0-9가-힣]/g, '_')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="container mx-auto px-4 py-8 max-w-6xl">
        {/* Header */}
        <div className="bg-white rounded-lg shadow-lg p-6 mb-8">
          <div className="flex items-center justify-between mb-4">
            <h1 className="text-3xl font-bold text-gray-900">📚 내 노트</h1>
            <div className="space-x-3">
              <Link href="/create" className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg transition-colors">
                새 노트 생성
              </Link>
              <Link href="/" className="bg-gray-500 hover:bg-gray-600 text-white px-4 py-2 rounded-lg transition-colors">
                홈으로
              </Link>
            </div>
          </div>
          <p className="text-gray-600">
            생성한 모든 학습 노트를 관리하고 다운로드할 수 있습니다.
          </p>
        </div>

        {/* Search and Controls */}
        <div className="bg-white rounded-lg shadow-lg p-6 mb-8">
          <div className="flex flex-col sm:flex-row gap-4">
            <div className="flex-1">
              <input
                type="text"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                placeholder="노트 제목, 채널명, 핵심 인사이트로 검색..."
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <div className="flex space-x-3">
              <div className="text-sm text-gray-600 self-center">
                총 {filteredNotes.length}개 노트
              </div>
              {savedNotes.length > 0 && (
                <button
                  onClick={clearAllNotes}
                  className="bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded-lg transition-colors"
                >
                  전체 삭제
                </button>
              )}
            </div>
          </div>
        </div>

        {/* Notes List */}
        {filteredNotes.length === 0 ? (
          <div className="bg-white rounded-lg shadow-lg p-8 text-center">
            <div className="text-6xl mb-4">📝</div>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              {savedNotes.length === 0 ? '저장된 노트가 없습니다' : '검색 결과가 없습니다'}
            </h2>
            <p className="text-gray-600 mb-6">
              {savedNotes.length === 0 
                ? 'YouTube 영상으로 첫 번째 학습 노트를 생성해보세요!'
                : '다른 검색어로 다시 시도해보세요.'
              }
            </p>
            {savedNotes.length === 0 && (
              <Link href="/create" className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-6 rounded-lg transition-colors">
                첫 노트 생성하기
              </Link>
            )}
          </div>
        ) : (
          <div className="space-y-6">
            {filteredNotes.map((note) => (
              <div key={note.id} className="bg-white rounded-lg shadow-lg p-6">
                <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between">
                  <div className="flex-1">
                    <h3 className="text-xl font-bold text-gray-900 mb-2">
                      {note.title}
                    </h3>
                    
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm text-gray-600 mb-4">
                      <div>
                        <span className="font-semibold">채널:</span> {note.channelTitle}
                      </div>
                      <div>
                        <span className="font-semibold">길이:</span> {note.duration}
                      </div>
                      <div>
                        <span className="font-semibold">생성일:</span> {new Date(note.createdAt).toLocaleDateString('ko-KR')}
                      </div>
                    </div>

                    <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-3 mb-4">
                      <div className="text-sm font-semibold text-yellow-800 mb-1">💡 핵심 인사이트</div>
                      <p className="text-yellow-700 text-sm">{note.keyInsight}</p>
                    </div>

                    <div className="text-sm text-gray-500">
                      구간 수: {note.sections?.length || 0}개
                    </div>
                  </div>

                  <div className="mt-4 lg:mt-0 lg:ml-6 flex flex-col space-y-2">
                    <a
                      href={note.youtubeUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded-lg transition-colors text-center text-sm"
                    >
                      🎬 원본 영상
                    </a>
                    
                    <button
                      onClick={() => downloadNote(note)}
                      className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg transition-colors text-sm"
                    >
                      📥 다운로드
                    </button>
                    
                    <button
                      onClick={() => deleteNote(note.id)}
                      className="bg-gray-600 hover:bg-gray-700 text-white px-4 py-2 rounded-lg transition-colors text-sm"
                    >
                      🗑️ 삭제
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Storage Info */}
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-6 mt-8">
          <h3 className="font-bold text-blue-800 mb-2">💾 저장 정보</h3>
          <ul className="space-y-1 text-sm text-blue-700">
            <li>• 모든 노트는 브라우저의 로컬 스토리지에 저장됩니다.</li>
            <li>• 브라우저 데이터를 삭제하면 노트도 함께 삭제됩니다.</li>
            <li>• 중요한 노트는 마크다운 파일로 다운로드하여 백업하는 것을 권장합니다.</li>
            <li>• 다른 기기에서는 노트에 접근할 수 없습니다.</li>
          </ul>
        </div>
      </div>
    </div>
  );
}